### PR TITLE
update kafka to 2.1.0 and jmeter to 5.0

### PR DESCRIPTION
**Pull request by jorgheymans**
fix resulting compilation errors

### CODE REVIEW

**Comment by jorgheymans** [comment]
the build errors result from the fact that it's unable to start Kafka during testing

**Comment by Nachiket90** [comment]
Thanks for your contribution. A thought before merging this request, Is it worth supporting very old versions of JMeter considering the future maintenance and life time of these JMeter versions. I would suggest people who are still with 2.x should move to JMeter latest at atleast 3.x version or use the fork.
 @jorgheymans, This is my opinion but 2.x can be supported if good amount of user base is still on 2.x.
@satishbhor what do you think?

**Comment by jorgheymans** [comment]
pepperbox is not in an easy spot given you're essentially tracking two tools : jmeter and kafka.

Performancewise for kafka it's worth having the option to use kafkaclient matching your server version, jmeter is less sensitive to this probably.

**Comment by satishbhor** [comment]
@Nachiket90 We should have old versions on new branch where latest on master. 
@jorgheymans Thanks for PR along with code change could you please  update document with version details?
@Nachiket90 Could you please tag master with kafka 9 and JMeter 3 ?

**Comment by Nachiket90** [comment]
@jorgheymans your proposal makes sense and we can support older versions considering their usage in industry. @satishbhor  I'll add tags to master.

**Comment by slachiewicz** [comment]
Maybe we can try to use Kafka 2.2 (released 22 March) - Kafka clients are backward compatible, so uses will be able to test with different server version and compare performance and compatibility easier.

**Comment by ankon** [comment]
I'm also trying to get pepper-box to run with Kafka 2.1.1/Jmeter 5.1.1, and I needed this in addition to the changes proposed to make the tests pass:
```diff
diff --git a/src/test/java/com/gslab/pepper/test/PepperBoxLoadGenTest.java b/src/test/java/com/gslab/pepper/test/PepperBoxLoadGenTest.java
index f080d5d..388d4ba 100644
--- a/src/test/java/com/gslab/pepper/test/PepperBoxLoadGenTest.java
+++ b/src/test/java/com/gslab/pepper/test/PepperBoxLoadGenTest.java
@@ -55,8 +55,9 @@ public class PepperBoxLoadGenTest {
         brokerProps.setProperty("broker.id", "0");
         brokerProps.setProperty("log.dirs", Files.createTempDirectory("kafka-").toAbsolutePath().toString());
         brokerProps.setProperty("listeners", "PLAINTEXT://" + BROKERHOST +":" + BROKERPORT);
+        brokerProps.setProperty("offsets.topic.replication.factor", "1");
         KafkaConfig config = new KafkaConfig(brokerProps);
         MockTime mock = new MockTime();
         kafkaServer = TestUtils.createServer(config, mock);
         //AdminUtils.createTopic(zkUtils, TOPIC, 1, 1, new Properties(), RackAwareMode.Disabled$.MODULE$);
 
diff --git a/src/test/java/com/gslab/pepper/test/PepperBoxSamplerTest.java b/src/test/java/com/gslab/pepper/test/PepperBoxSamplerTest.java
index f85dfe7..559a74b 100644
--- a/src/test/java/com/gslab/pepper/test/PepperBoxSamplerTest.java
+++ b/src/test/java/com/gslab/pepper/test/PepperBoxSamplerTest.java
@@ -61,8 +61,9 @@ public class PepperBoxSamplerTest {
         brokerProps.setProperty("broker.id", "0");
         brokerProps.setProperty("log.dirs", Files.createTempDirectory("kafka-").toAbsolutePath().toString());
         brokerProps.setProperty("listeners", "PLAINTEXT://" + BROKERHOST +":" + BROKERPORT);
+        brokerProps.setProperty("offsets.topic.replication.factor", "1");
         KafkaConfig config = new KafkaConfig(brokerProps);
         MockTime mock = new MockTime();
         kafkaServer = TestUtils.createServer(config, mock);
         //AdminUtils.createTopic(zkUtils, TOPIC, 1, 1, new Properties(), RackAwareMode.Disabled$.MODULE$);
```

Without these changes Kafka fails to start, and logs this repeatedly:
~~~~
16:14:54.796 [kafka-request-handler-7] ERROR kafka.server.KafkaApis - [KafkaApi-0] Number of alive brokers '1' does not meet the required replication factor '3' for the offsets topic (configured via 'offsets.topic.replication.factor'). This error can be ignored if the cluster is starting up and not all brokers are up yet.
~~~~

**Comment by klawyMarcin** [comment]
Test crashes for me at shutting down zkServer:
`serializedKeyMessageSamplerTest(com.gslab.pepper.test.PepperBoxSamplerTest)  Time elapsed: 9.098 sec  <<< ERROR!
java.nio.file.FileSystemException: C:\Users\klawy\AppData\Local\Temp\kafka-9041317231624614976\version-2\log.1: process cannot access the file because it is being used by another process

	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
	at sun.nio.fs.WindowsFileSystemProvider.implDelete(WindowsFileSystemProvider.java:269)
	at sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:103)
	at java.nio.file.Files.delete(Files.java:1126)
	at org.apache.kafka.common.utils.Utils$1.visitFile(Utils.java:645)
	at org.apache.kafka.common.utils.Utils$1.visitFile(Utils.java:634)
	at java.nio.file.Files.walkFileTree(Files.java:2670)
	at java.nio.file.Files.walkFileTree(Files.java:2742)
	at org.apache.kafka.common.utils.Utils.delete(Utils.java:634)
	at kafka.zk.EmbeddedZookeeper.shutdown(EmbeddedZookeeper.scala:63)
	at com.gslab.pepper.test.PepperBoxSamplerTest.teardown(PepperBoxSamplerTest.java:277)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:33)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
`

But when I skip tests, it seems to work just OK

**Pull request closed without merging**
