### PR TITLE
added .gitignore, added net.sf.jwordnet dependency, added maven.compi…

### PR DESCRIPTION
**Pull request by filipecosta90**
…ler.target to complie with java.time ( > 1.8 )

### CODE REVIEW

**Comment by satishbhor** [comment]
@filipecosta90 could u please explain purpose of this PR ?

**Comment by filipecosta90** [comment]
hi @satishbhor, i was trying to compile your code with java8 env and experienced some problems regarding the compilation. this PR goes towards trying to resolve those issues. 
kind regards, 
filipe

**Comment by satishbhor** [comment]
We are already supporting JDK 8 can you explain what exactly issue you was facing ?

**Comment by Nachiket90** [comment]
Hi @filipecosta90,

Can you elaborate on PR and issues you faced? Also what is expected out of lite version of this plugin?

**Comment by filipecosta90** [comment]
hi there @Nachiket90, please ignore my second commit as i was removing some complexity that i don't need for my specific tests on jmeter. 
I will cancel this merge request and will create another only with the changes that i find useful. 
Please take in consideration that with the kafka acks as they are now on your current plugin version you don't wait for an ack and consequently don't count that time on the request. I resolved that issue defining an latch and an callback function. 
As i said, i will close this merge request. re-fork and only update accordingly during tommorow. 
kind regards,

**Comment by filipecosta90** [comment]
hi @Nachiket90 
please refer to:
https://github.com/GSLabDev/pepper-box/pull/21

**Pull request closed without merging**
